### ISSUE TITLE
mocap_processing.ops

### ISSUE THREAD

**Issue by VhalPurohit** [facebookresearch/fairmotion#28]
Hi
The tutorial in your readme file mentions
`from mocap_proceessing.ops import motion as motion_ops

translated_motion = motion_ops.translate(motion, np.array([1, 1, 1]))
sliced_motion = motion_ops.cut(translated_motion, 10, 20)`

I went through your git but couldn't find a module named 
`mocap_processing`. I was wondering what that was about

**Comment by dpacgopinath** [comment]
Hi @VhalPurohit , thanks for reporting the issue! This is a typo -- `mocap_processing` was the name of an earlier version of the project. Simply replacing `mocap_processing` with `fairmotion` should work. I have submitted a PR with the change https://github.com/facebookresearch/fairmotion/pull/30
