### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by ManifoldFR** [facebookresearch/fairmotion#35]
Hi,

I noticed when trying to install (either from PyPI or after git cloning) that this requires PyTorch 1.4 whereas the most recent is 1.6. Would it be possible to bump the torch version ?

**Comment by dpacgopinath** [comment]
Hi @ManifoldFR , bumping PyTorch version seems to break the dataloader in `fairmotion/tasks/motion_prediction/dataset.py` due to possible changes in `torch.utils.data`. I agree that it would be ideal to bump to version 1.6, let me look into fixing this. Thanks for flagging this!
