### ISSUE TITLE
Seq2seq fforward() takes from 2 to 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by lesthad666** [facebookresearch/fairmotion#36]
when I run the model in "model prediction" task with parameters by default it throws me this

epoch_loss = 0
for iterations, (src_seqs, tgt_seqs) in enumerate(dataset["train"]):
    model.eval()
    src_seqs, tgt_seqs = src_seqs.to(device), tgt_seqs.to(device)
    outputs = model(src=src_seqs,tgt= tgt_seqs)

TypeError: forward() takes from 2 to 6 positional arguments but 7 were given

**Comment by dpacgopinath** [comment]
Thanks for raising this issue. I will take a look!

**Comment by dpacgopinath** [comment]
@lesthad666 feel free to review https://github.com/facebookresearch/fairmotion/pull/39 which contains the fix
