### ISSUE TITLE
The frame skipping in extract_manual_features() is 30 or 1?

### ISSUE THREAD

**Issue by liruilong940607** [facebookresearch/fairmotion#50]
From the line [here](https://github.com/facebookresearch/fairmotion/blob/b3e58096054baa86726569de1f7c5a2e440131fb/fairmotion/tasks/clustering/generate_features.py#L27) it seems like you are extracting features every 30 frames. Yet from this line [here](https://github.com/facebookresearch/fairmotion/blob/master/fairmotion/tasks/clustering/generate_features.py#L118) it seems like you want to do per-frame feature extraction. 

I'm confused that are these two lines contradictory to each other?

**Comment by dpacgopinath** [comment]
Apologies for the delay in addressing this.  You're right about the contradiction. I have fixed it in PR #53
