### ISSUE TITLE
loading motion in xyz format

### ISSUE THREAD

**Issue by Neptune-Trojans** [facebookresearch/fairmotion#62]
Hi,

I have skeleton motion data in xyz format.
Is that possible to load this motion data into your package ? If yes can you provide some info how to do it ?  

Thanks a lot!

**Comment by fabienbaradel** [comment]
Hi @Neptune-Trojans ,
Did you find a way to have skeleton motion in xyz format?
Thanks for your help,

**Comment by Neptune-Trojans** [comment]
Hi @fabienbaradel 

No I didn't find way to do xyz with backward kinematics and loading into this library.
what is worked for me at the end: I trained on rotation matrices dataset and I used my base skeleton and then loaded the generated data into this package.

**Comment by fabienbaradel** [comment]
Good to know, thanks for your answer
