### ISSUE TITLE
Rendering artifacts after MSAA's commit

### ISSUE THREAD

**Issue by mJones00** [facebookresearch/fairmotion#72]
Since "MSAA and mouse sensitivity were added" commit, rendering issues are noticed. I'm not sure of the exact cause of it though.
After 837f5466cf2bc2d7a9f95fc50c035257ec4c5232
<img width="636" alt="after" src="https://user-images.githubusercontent.com/91318638/156621152-70f26fd3-eb9a-4d3b-b21b-766202566a25.png">
before 837f5466cf2bc2d7a9f95fc50c035257ec4c5232
<img width="640" alt="before" src="https://user-images.githubusercontent.com/91318638/156621157-132acba8-283b-4fbe-a940-f2321e2defc7.png">

**Comment by Jungdam** [comment]
Do you also have such problem when MSAA is turned off?

**Comment by mJones00** [comment]
MSAA is turned off by default in the Viewer constructor. The comparison I showed was without changing any parameter. Just using the versions before and after the commit with everything as default.

**Comment by Jungdam** [comment]
We found that some basic 'Smoothing' settings in OpenGL cause such artifacts.
Now, you can use either basic or smoothed versions by changing the 'msaa' argument.

Can you try the latest version, and let us know if it works for you?

**Comment by mJones00** [comment]
Now, MSAA is working as intended:
MSAA disabled:
<img width="639" alt="after" src="https://user-images.githubusercontent.com/91318638/156801578-10614047-58f3-42d2-839e-bf439632e0f4.png">
MSAA enabled:
<img width="639" alt="msaa" src="https://user-images.githubusercontent.com/91318638/156801626-789ce63f-13bf-4f36-a8c5-f8c987c4db89.png">

should probably add msaa as a parameter for other visualizers as well.
